### PR TITLE
triangle: return int, fixes #164

### LINKED ISSUE #164: All tests pass with no code submitted, in x86-64 Assembly - Triangle
In the browser code editor, all tests pass if you do not submit any code. [This](https://exercism.org/tracks/x86-64-assembly/exercises/triangle/solutions/adep3zjh) user did just that and it has passed. 

I have not tested this with a CLI submission.

### PR DESCRIPTION
**Pull request by sudhackar**
As discussed in #164 - this should enforce returning 1/0 instead of true/false.

### CODE REVIEW

**Review by ErikSchierboom — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
CI is failing

**Comment by sudhackar** [comment]
will fix

**Comment by sudhackar** [comment]
CI passed. ready to merge

**Comment by ErikSchierboom** [comment]
Thanks!

**Pull request merged**
