### PR TITLE
Add .note.GNU-stack section to every exercise

### PR DESCRIPTION
**Pull request by 0x28**
This PR solves issue #160.

### CODE REVIEW

**Review by bergjohan — APPROVED** [review]

**Comment by bergjohan** [comment]
Thank you for the PR, looks good!

@ErikSchierboom Could you help with merging this?

**Comment by bergjohan** [comment]
Noticed in another PR that this fails for macOS. I think we need to ifidn it for elf64 only:
```
%ifidn __OUTPUT_FORMAT__,elf64
section .note.GNU-stack noalloc noexec nowrite progbits
%endif
```

**Comment by 0x28** [comment]
@bergjohan done.

**Review by bergjohan — APPROVED** [review]

**Comment by bergjohan** [comment]
Perfect, thank you!

**Review by ErikSchierboom — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
Side note: @bergjohan turns out you don't have write permissions anymore. I seem to recall us having discussed this. Was this by your request, or did we forget to give you permissions?

**Comment by bergjohan** [comment]
@ErikSchierboom They were removed because I wasn't active as a maintainer. We discussed it a while back in another PR, and I decided to wait.
But maybe it would be better if I got permissions again, so I don't have to ping you in every PR.

**Comment by neenjaw** [comment]
?

**Comment by ErikSchierboom** [comment]
I did. Fail!

**Pull request merged**
