### PR TITLE
Add .gitignore for exercises

### PR DESCRIPTION
**Pull request by bergjohan**
Ref: #73

### CODE REVIEW

**Comment by bergjohan** [comment]
@nathanchere Does this look ok?

**Comment by kotp** [comment]
Should we also add a check in [bin/verify-exercises](https://github.com/exercism/x86-64-assembly/blob/master/bin/verify-exercises) for the `.gitignore` file per exercise?  I don't see a generator, but this might be some tooling so that this stays consistent, or at least not missed.

**Comment by bergjohan** [comment]
You mean check that the file exists for every exercise?

A tool that verifies that the contents of some files are the same across all exercises would also be useful. The `Makefile` and the contents of the `vendor` directory should be the same for every exercise.

I usually just `cp -r exercises/hello-world <slug-of-new-exercise>` when creating a new exercise.

**Comment by kotp** [comment]
Yeah.  In some tracks, have a "generator" command that helps to build the tests file, and some other `bin` content to set up things like git hooks, etc.  Having central tooling means others get the benefit of your known-to-work-well-enough workflow.

**Comment by bergjohan** [comment]
Yeah, I've got a generator for generating test files, see [https://github.com/exercism/x86-64-assembly/blob/master/generators/generate](https://github.com/exercism/x86-64-assembly/blob/master/generators/generate). I should probably add more tools, but I'm pretty busy with v3 at the moment :)

**Comment by kotp** [comment]
> Yeah, I've got a generator for generating test file

Ah, I missed it, though I did look in `bin` for the tooling that would be executed. Ruby has their executables in `bin`.

**Comment by bergjohan** [comment]
Yeah, that might be a better place for it.

I'll merge this, and figure out the tooling in another PR.

Thank you for having a look at this! :)

**Pull request merged**
