### PR TITLE
Add support for Apple ARM

### PR DESCRIPTION
**Pull request by bergjohan**
Continuation of #101

### CODE REVIEW

**Comment by bergjohan** [comment]
@ErikSchierboom I haven't gotten my write permissions yet, could we get this one merged? And also close #101 as duplicate?

**Review by ErikSchierboom — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
> I haven't gotten my write permissions yet, 

We'll get on it. Should be done soon. I'll let you know when!

**Comment by ErikSchierboom** [comment]
> And also close https://github.com/exercism/x86-64-assembly/pull/101 as duplicate?

Done

**Comment by ErikSchierboom** [comment]
>  I haven't gotten my write permissions yet

Fixed!

**Comment by bergjohan** [comment]
Thank you! :)

**Pull request merged**
